# Table 3. Inclusion relationship and similarity between alarms of original Infer (A) and data-driven Infer (B).

## Pre-requisite
* `/vagrant/Table1/data` and `/vagrant/Table2/data`
  (Automatically generated by `/vagrant/Table1/run.sh` and `/vagrant/Table2/run.sh`, respectively.)

* Compute the similarity and create the result table.
```bash
./run.sh
```

